version: '3.4'

services:
  laravel-once:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - '8000:8000'
    volumes:
      - .:/home/devuser/package:delegated
      - ~/.ssh:/home/devuser/.ssh:cached
      - ~/.gitconfig:/home/devuser/.gitconfig

    networks:
      - app-network
networks:
  app-network:
    driver: bridge
